@startuml

skinparam maxMessageSize 45
skinparam lifelineStrategy nosolid
skinparam style strictuml
hide footbox

header Bloqs
footer Page %page% of %lastpage%

title Sign In example

hide unlinked

actor User as User
participant Client as Client
box "Auth micro service" #transparent
participant "Authorization API" as Auth
database "Credentials DB" as Creds
database "Secrets DB" as Secrets
end box

autonumber
[-> Auth: Requests to create a new account with the credentials given
Auth -> Auth: Validates Credentials
alt valid credentials
    Auth -> Creds: Verifies that the credentials exist
    activate Creds
    return results
    destroy Creds
    [<- Auth: Responds with the success status
else invalid credentials
    [<- Auth: Responds with the error status
end

newpage Sign Off example

newpage Log In example

newpage Log Off example

newpage Token validation example

@enduml
